//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments_Page_Files
    {
        public System.Guid FileID { get; set; }
        public string Attachment_page_id { get; set; }
        public string Extension { get; set; }
        public System.DateTime DateUploaded { get; set; }
    
        public virtual Attachments_pages Attachments_pages { get; set; }
    }
}
