//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments_pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachments_pages()
        {
            this.Attachments_Page_Files = new HashSet<Attachments_Page_Files>();
        }
    
        public string Attachment_page_id { get; set; }
        public int Attachment_id { get; set; }
        public string Number { get; set; }
        public string Cuit { get; set; }
        public string Customer_name { get; set; }
        public string Amount { get; set; }
        public string Date { get; set; }
        public System.DateTime Reg_date { get; set; }
        public bool IsInvoice { get; set; }
        public bool IsAssigned { get; set; }
        public bool IsProcessing { get; set; }
        public bool IsVerified { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> AssociatedDocumentTypeID { get; set; }
        public bool IsGreater { get; set; }
        public Nullable<int> ProviderCategoryID { get; set; }
        public int CurrencyID { get; set; }
        public bool HasAttached { get; set; }
    
        public virtual attachments attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments_Page_Files> Attachments_Page_Files { get; set; }
    }
}
