//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public attachments()
        {
            this.Attachments_pages = new HashSet<Attachments_pages>();
        }
    
        public int attachment_id { get; set; }
        public string filename { get; set; }
        public string pathfile { get; set; }
        public int received_emails_id { get; set; }
        public int status_attachment_id { get; set; }
        public string attachment_GUID { get; set; }
    
        public virtual status_attachment status_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments_pages> Attachments_pages { get; set; }
        public virtual received_emails received_emails { get; set; }
    }
}
