//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrats()
        {
            this.printers = new HashSet<printers>();
        }
    
        public int contrats_id { get; set; }
        public int contrats_number { get; set; }
        public Nullable<long> customer_number { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string biller { get; set; }
        public string business_name { get; set; }
        public string contrats_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<printers> printers { get; set; }
    }
}
