//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPEntities : DbContext
    {
        public RPEntities()
            : base("name=RPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD> AD { get; set; }
        public virtual DbSet<attachments> attachments { get; set; }
        public virtual DbSet<Attachments_Page_Files> Attachments_Page_Files { get; set; }
        public virtual DbSet<Attachments_pages> Attachments_pages { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<contrats> contrats { get; set; }
        public virtual DbSet<departaments> departaments { get; set; }
        public virtual DbSet<departaments_users> departaments_users { get; set; }
        public virtual DbSet<Email_Employees> Email_Employees { get; set; }
        public virtual DbSet<employee_reg_local> employee_reg_local { get; set; }
        public virtual DbSet<flow_record> flow_record { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<invoice_files> invoice_files { get; set; }
        public virtual DbSet<invoice_status> invoice_status { get; set; }
        public virtual DbSet<InvoiceAudit> InvoiceAudit { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Paycheck> Paycheck { get; set; }
        public virtual DbSet<printers> printers { get; set; }
        public virtual DbSet<PropertysPaycheck> PropertysPaycheck { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<providers_email> providers_email { get; set; }
        public virtual DbSet<received_emails> received_emails { get; set; }
        public virtual DbSet<RejectionComments> RejectionComments { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<status_attachment> status_attachment { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_service> type_service { get; set; }
        public virtual DbSet<TypeOfForm> TypeOfForm { get; set; }
        public virtual DbSet<UploadedFiles> UploadedFiles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
