//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_files
    {
        public int invoice_files_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string invoice_path { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
