//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAudit
    {
        public int InvoiceAuditID { get; set; }
        public System.DateTime AuditDate { get; set; }
        public int UserID { get; set; }
        public int InvoiceID { get; set; }
        public int DepartamentID { get; set; }
        public int ActionType { get; set; }
        public string UserName { get; set; }
    
        public virtual departaments departaments { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
