//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.Comments = new HashSet<Comments>();
            this.flow_record = new HashSet<flow_record>();
            this.invoice_files = new HashSet<invoice_files>();
            this.InvoiceAudit = new HashSet<InvoiceAudit>();
            this.RejectionComments = new HashSet<RejectionComments>();
        }
    
        public int invoice_id { get; set; }
        public string invoice_number { get; set; }
        public string invoice_cuit { get; set; }
        public string invoice_date { get; set; }
        public Nullable<double> invoice_amount { get; set; }
        public Nullable<int> invoice_status_id { get; set; }
        public Nullable<int> departament_id { get; set; }
        public Nullable<bool> amount_check { get; set; }
        public Nullable<int> attachment_id { get; set; }
        public string order_num { get; set; }
        public bool partial_assignment { get; set; }
        public string InvoiceFile { get; set; }
        public string business_name { get; set; }
        public bool isGreater { get; set; }
        public int CurrencyID { get; set; }
        public int AssociatedDocumentTypeID { get; set; }
        public int ProviderCategoryID { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flow_record> flow_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_files> invoice_files { get; set; }
        public virtual invoice_status invoice_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAudit> InvoiceAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectionComments> RejectionComments { get; set; }
    }
}
