//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paycheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paycheck()
        {
            this.PropertysPaycheck = new HashSet<PropertysPaycheck>();
        }
    
        public int ID { get; set; }
        public string DocumentID { get; set; }
        public int UserID { get; set; }
        public bool IsChecked { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int EmployeeLocalID { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertysPaycheck> PropertysPaycheck { get; set; }
    }
}
