//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class printers
    {
        public int printer_id { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> installation_date { get; set; }
        public int contrats_id { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        public virtual contrats contrats { get; set; }
    }
}
