//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class received_emails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public received_emails()
        {
            this.attachments = new HashSet<attachments>();
        }
    
        public int received_emails_id { get; set; }
        public string email_address { get; set; }
        public string email_subject { get; set; }
        public string email_body { get; set; }
        public System.DateTime email_date { get; set; }
        public int email_attachment_quantity { get; set; }
        public Nullable<int> provider_id { get; set; }
        public bool Readed { get; set; }
        public Nullable<System.DateTime> ReadedDate { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> received_email_GUID { get; set; }
        public string SenderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachments> attachments { get; set; }
    }
}
