//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedFiles
    {
        public System.Guid UploadedFileID { get; set; }
        public string FileName { get; set; }
        public string OriginalName { get; set; }
        public System.DateTime Uploaded { get; set; }
    }
}
